language: go
sudo: false
go:
  - 1.7
  - tip
install:
  - go get -v github.com/golang/lint/golint
  - go get -d -t -v ./...
  - go build -v ./...
script:
  - go vet ./...
  - $HOME/gopath/bin/golint .
  - go test -v ./...
